import { Hero } from './hero';

export const HEROES:Hero[] = [
    {id: 1, name: 'Albert'},
    {id: 2, name: 'Andy'},
    {id: 3, name: 'Einstein'},
    {id: 4, name: 'Wes'},
    {id: 5, name: 'Andreau'},
    {id: 6, name: 'James'},
    {id: 7, name: 'Lee'},
    {id: 8, name: 'Aria'},
    {id: 9, name: 'Ron'},
    {id: 10, name: 'Robert'},
    {id: 11, name: 'Brown'},
    {id: 12, name: 'Jill'},
    {id: 13, name: 'White'},
    {id: 14, name: 'John'},
    {id: 15, name: 'Andreas'},
    {id: 16, name: 'Sarah'},
    {id: 17, name: 'Jack'},
    {id: 18, name: 'Martina'},
    {id: 19, name: 'Rick'},
    {id: 20, name: 'Jasmin'},
    {id: 19, name: 'Johny'},
    {id: 20, name: 'Sam'},
    {id: 19, name: 'Crowlie'},
    {id: 20, name: 'Hansen'},
];
