import { Hero } from './hero';

export const HEROES:Hero[] = [
    {id: 1, name: 'Albert'},
    {id: 2, name: 'Andy'},
    {id: 3, name: 'Einstein'},
//     {id: 4, name: 'Wes'},
//     {id: 5, name: 'Andreau'},
//     {id: 6, name: 'James'},
//     {id: 7, name: 'Lee'},
//     {id: 8, name: 'Aria'},
    {id: 9, name: 'Ron'},
    {id: 10, name: 'Robert'},
//     {id: 11, name: 'Brown'},
//     {id: 12, name: 'Jill'},
//     {id: 13, name: 'White'},
    {id: 14, name: 'John'},
    {id: 15, name: 'Andreas'},
//     {id: 16, name: 'Sarah'},
//     {id: 17, name: 'Jack'},
//     {id: 18, name: 'Martina'},
//     {id: 19, name: 'Rick'},
    {id: 20, name: 'Jasmin'},
    {id: 21, name: 'Johny'},
    {id: 22, name: 'Sam'},
    {id: 23, name: 'Crowlie'},
//     {id: 24, name: 'Hansen'},
//     {id: 25, name: 'Moses'},
//     {id: 26, name: 'Mary'},
//     {id: 27, name: 'Morphy'},
//     {id: 28, name: 'Katrina'},
//     {id: 29, name: 'Joseph'},
    {id: 30, name: 'Josiphine'},
    {id: 31, name: 'Mohit'},
    {id: 32, name: 'Amina'},
//     {id: 33, name: 'Sarah'},
//     {id: 34, name: 'Monalisa'},
//     {id: 35, name: 'James'},
//     {id: 36, name: 'Mona'},
//     {id: 37, name: 'Abraham'},
    {id: 38, name: 'Billy'},
    {id: 37, name: 'Nathan'},
//     {id: 38, name: 'Jolly'},
//     {id: 39, name: 'Jelly'},
//     {id: 40, name: 'Arij'},
//     {id: 41, name: 'Coco'},
//     {id: 42, name: 'Suraj'},
    {id: 43, name: 'Mina'},
//     {id: 42, name: 'Imon'},
//     {id: 43, name: 'Bayezid'},
];
